env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
  - plugin:@next/next/recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
rules:
  {'react/react-in-jsx-scope': 'off', 'require-jsdoc': 'off', 'prettier/prettier': 'error'}
